// Generated by tools/narration.mjs from briefing.script.ts. Do not edit by hand.
// Adam - Deep English Story Voice (ElevenLabs eleven_multilingual_v2), 94.022 s, normalised to -17 LUFS.
import type { BriefingCues } from './briefing.script';

export const BRIEFING_CUES: BriefingCues = {
  duration: 94.022,
  lines: {
    who: { start: 0.35, end: 3.27, hash: 'd292996e' },
    cast: { start: 4.02, end: 15.75, hash: 'bc182b39' },
    cams: { start: 16.25, end: 19.544, hash: 'a2059480' },
    clock: { start: 20.444, end: 25.924, hash: '6630e356' },
    safe: { start: 26.824, end: 35.384, hash: 'b9b12248' },
    truth: { start: 36.284, end: 45.757, hash: '0c299e6e' },
    senses: { start: 46.307, end: 53.907, hash: '34c00460' },
    choices: { start: 54.457, end: 61.727, hash: '5bffdcc2' },
    endings: { start: 62.727, end: 64.717, hash: '46658d35' },
    morning: { start: 65.317, end: 69.857, hash: '696cdff6' },
    rational: { start: 70.407, end: 77.818, hash: 'e8582c72' },
    came_through: { start: 78.368, end: 85.912, hash: '998125ff' },
    missing: { start: 86.462, end: 90.762, hash: 'aa8fbaad' },
    close: { start: 91.862, end: 93.422, hash: '46b8d21c' },
  },
};
